<!-- Localized -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head profile="http://gmpg.org/xfn/11">
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | Tim Friday | Landscape design"
        </script>

        <!-- BaseHref :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
        <!-- BaseHref :: End -->

        <!-- CanonicalTag :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
        <!-- CanonicalTag :: End -->

        <!-- Meta Tags :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
        <!-- Meta Tags :: End -->

        <!-- Meta Geo Tags :: Start -->
        <meta name="geo.region" content="DE-NI" />
        <meta name="geo.placename" content="Andelsbuch" />
        <meta name="geo.position" content="52.80912;9.14234" />
        <meta name="ICBM" content="52.80912, 9.14234" />
        <!-- Meta Geo Tags :: End -->

        <!-- Windows 8 Tile :: Start -->
        <meta name="application-name" content="moraso CMS" /> 
        <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <!-- Windows 8 Tile :: End -->

        <!-- CSS :: Start -->
        <link rel="stylesheet" href="/skin/css/style.css" />
        <link rel="stylesheet" id="superfish-css"  href="/skin/js/superfish/superfish-2404.css" type="text/css" media="all" />
        <!-- CSS :: End -->

        <!-- JS :: Start -->
        <script src="/skin/js/vendor/prefixfree.min.js"></script>
        <script type="text/javascript" src="/skin/js/jquery-1.9.0.min.js"></script>
        <script type="text/javascript" src="/skin/js/jquery.mousewheel-3.0.6.pack.js"></script>
        <script type="text/javascript" src="/skin/source/jquery.fancybox.js?v=2.1.4"></script>
        <link rel="stylesheet" type="text/css" href="/skin/source/jquery.fancybox.css?v=2.1.4" media="screen" />
        <link rel="stylesheet" type="text/css" href="/skin/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
        <script type="text/javascript" src="/skin/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
        <link rel="stylesheet" type="text/css" href="/skin/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
        <script type="text/javascript" src="/skin/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
        <script type="text/javascript" src="/skin/source/helpers/jquery.fancybox-media.js?v=1.0.5"></script>

        <script type='text/javascript'>
            storyBump = 70; 
            trainerBump = 200; 
            parallaxHeight = 1000; 
        </script>	

        <script type="text/javascript" src="/skin/js/jquery.localscroll-1.2.7-min.js"></script>
        <script type="text/javascript" src="/skin/js/parallax.js"></script>
        <script type="text/javascript" src="/skin/js/jquery.scrollTo-1.4.2-min.js"></script>
        <script type="text/javascript" src="/skin/js/jquery.inview.js"></script>

        <script type="text/javascript">
            $(document).ready(function(){
	            $('.fancybox').fancybox();

	            function setTopMargin() {
		            var headerHeight = $('#headerBar').height();
		            $('body.home #container').css('margin-top',headerHeight);
		        }
	
		        var headerHeightNeg = 0 - $('#headerBar').height();
		        $('#nav').localScroll({offset: {left: 0, top: headerHeightNeg}});
		        $('#mainNav').localScroll({offset: {left: 0, top: headerHeightNeg}});
		        $('#logo').localScroll({offset: {left: 0, top: headerHeightNeg}});
		        $('.story .blockText').css('margin-top',storyBump);
		        setTopMargin();
		
		        $(window).resize(function() { setTopMargin(); });
		    });
        </script>
        <!-- JS :: End -->


        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body class="home blog">
    <div id="container" class="clearfix">

        <!-- Header :: Start -->
        <script type="application/x-moraso" src="Template:Header">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/header/default.phtml 
        </script>
        <!-- Header :: End -->

        <!-- Content :: Start -->
        <script type="application/x-moraso" src="Template:Content">
            defaultTemplate = start

            template.start.name = Start
            template.start.file = templates/content/start.phtml 
        </script>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <script type="application/x-moraso" src="Template:Footer">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/footer/default.phtml 
        </script>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        
        <!-- JS :: End -->

    </div>
    </body>
</html>
