<div style="margin-top: 300px;">
    <div class="row">    
        <div class="large-9 push-3 columns">
            <script type="application/x-moraso" src="Image:Bild">
                width = 300
                height = 200
                render = 1
                template = Standard
            </script>            

            <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
                tag = h2
            </script>

            <hr />
            <script type="application/x-moraso" src="HTML.Content:Einleitung"></script>
            <script type="application/x-moraso" src="HTML.Content:Fliesstext"></script>
        </div>
    </div>
</div>