<div id="mainNav">
	<div class="menu-main-container">
		<ul id="menu-main" class="sf-menu">

			<li id="blockLink2" class="menu-item-2"><a href="#block2">The Service</a></li>
			<li id="blockLink3" class="menu-item-3"><a href="#block3">Portfolio</a></li>
			<li id="blockLink4" class="menu-item-4"><a href="#block4">About</a></li>
			<li id="blockLink5" class="menu-item-5"><a href="#block5">Free Advice</a></li>
			<li id="blockLink6" class="menu-item-6"><a href="#block6">Partners</a></li>
			<li id="blockLink7" class="menu-item-7"><a href="#block7">Contact</a></li>
			<li id="" 			class="menu-item-8"><a href="#">EN</a>&nbsp;|&nbsp;<a href="#">DE</a></li>
		</ul>
	</div>
</div>