<div id="footer" class="clearfix">
	<div class="main clearfix">
    	<div id="tia_pixelscroll-3" class="oneThird widget_tia_pixelscroll footerBox widgetBox">
    		<p class="pixelsscrolled">  
	    		<!-- <span class="pixelscrollOne">You have scrolled</span>
	    		<span class="pixelscrollMid"><span id="pixels">0</span> pixels</span>
	    		<span class="pixelscrollTwo">of beauty.</span> -->
	    	</p>
	    </div>        				
	</div><!-- end footer main -->
	<div class="secondary clearfix">
		<div id="socialNetworks"><span class="left">&copy; 2013 <a href="#block1"><strong>irrsinn</strong></a> All Rights Reserved.</span>
			<a href="http://www.facebook.com/" title="on facebook"><img src="/skin/images/icons/socialmedia/facebook-20.png" alt="facebook" /></a>
			<a href="http://www.twitter.com" title="on twitter"><img src="/skin/images/icons/socialmedia/twitter-20.png" alt="twitter" /></a>
			<a href="https://plus.google.com/" title="on Google"><img src="/skin/images/icons/socialmedia/google-20.png" alt="Google" /></a>
		</div>									
	</div><!-- end footer secondary-->
</div><!-- end footer -->